name: Major Tag

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "v*.*.*"

jobs:
  major-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: oxHive/pipelines/.github/actions/major-tag@v3
        with:
          token: ${{ secrets.MAJOR_TAG_TOKEN }}
