name: Rust Check

on:
  workflow_call:
    inputs:
      fail-under-coverage:
        description: Minimum code coverage percentage
        type: number
        default: 60

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy -- -D warnings

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-tarpaulin
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin

      - name: Check coverage
        run: cargo tarpaulin --out Xml --fail-under ${{ inputs.fail-under-coverage }}
